import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({user}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{user.displayName}</h1>
      <h1>{user.email}</h1>
      <img src={user.imgurl} alt="user"/>

    </div>
  )
}


export async function getServerSideProps({params}){
  try {
    const res = await fetch(`https://api.vdev.in/user/${params.user}`)
    var data = await res.json()
  } catch (error) {
    console.log(error)
  }
  if (!data) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }
  return{
    props:{user : data}
  }
}