import Head from 'next/head'

export default function Home({ user }) {
  return (
    <div className='container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <h1>{user.displayName}</h1>
      <h1>{user.email}</h1>
      <img src={user.imgurl} alt="user" />

    </div>
  )
}


export async function getServerSideProps({ params }) {
  try {
    const res = await fetch(`https://api.vdev.in/user/${params.user}`)
    var data = await res.json()
  } catch (error) {
    console.log(error)
  }
  if (!data) {
    return {
      redirect: {
        destination: '/',
        permanent: false,
      },
    }
  }
  return {
    props: { user: data }
  }
}